import { CategoryQuestionModel } from "./CategoryQuestionModel";

export interface CategoryModel {
  name: string;
  imgUrl: string;
  questions: CategoryQuestionModel[];
}

export const defaultCategories = () => {
  return [
    {
      name: "Shonen Anime",
      imgUrl:
        "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dBsDWUcdfbuZwglgyeeQ9ChRoS4.jpg",
      questions: [
        {
          questionId: 1,
          showName: "Shonen Anime",
          score: 10,
          question: "Who is the main protagonist of 'Naruto'?",
          answer: "Naruto Uzumaki",
          hints: [
            "he is a ninja",
            "he has a dream to become Hokage",
            "he has a signature jutsu called Rasengan",
          ],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 2,
          showName: "Shonen Anime",
          score: 10,
          question: "What is the name of Goku's rival in 'Dragon Ball Z'?",
          answer: "Vegeta",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 3,
          showName: "Shonen Anime",
          score: 10,
          question: "What is the name of Luffy's brother in 'One Piece'?",
          answer: "Ace",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 4,
          showName: "Shonen Anime",
          score: 20,
          question: "What is the name of the village in 'Naruto'?",
          answer: "Konoha (Hidden Leaf Village)",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 5,
          showName: "Shonen Anime",
          score: 20,
          question: "Who is the captain of the 11th Division in 'Bleach'?",
          answer: "Kenpachi Zaraki",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 6,
          showName: "Shonen Anime",
          score: 30,
          question:
            "What is the name of the titan-slaying weapon in 'Attack on Titan'?",
          answer: "ODM Gear (Omni-Directional Mobility Gear)",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 7,
          showName: "Shonen Anime",
          score: 40,
          question:
            "What is the name of the demon inside Tanjiro's sister in 'Demon Slayer'?",
          answer: "Nezuko Kamado",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 8,
          showName: "Shonen Anime",
          score: 50,
          question:
            "What is the name of the ultimate technique of Goku in 'Dragon Ball Super'?",
          answer: "Ultra Instinct",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
      ],
    },
    {
      name: "Studio Ghibli",
      imgUrl:
        "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dBsDWUcdfbuZwglgyeeQ9ChRoS4.jpg",
      questions: [
        {
          questionId: 8,
          showName: "Studio Ghibli",
          score: 10,
          question: "What is the name of the cat bus in 'My Neighbor Totoro'?",
          answer: "Catbus",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 9,
          showName: "Studio Ghibli",
          score: 10,
          question: "What is the name of the bathhouse in 'Spirited Away'?",
          answer: "Aburaya",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 10,
          showName: "Studio Ghibli",
          score: 20,
          question:
            "What is the name of the cursed prince in 'Princess Mononoke'?",
          answer: "Ashitaka",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 11,
          showName: "Studio Ghibli",
          score: 20,
          question:
            "What is the name of the witch in 'Kiki's Delivery Service'?",
          answer: "Kiki",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 12,
          showName: "Studio Ghibli",
          score: 30,
          question:
            "What is the name of the spirit that helps Chihiro in 'Spirited Away'?",
          answer: "Haku",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 13,
          showName: "Studio Ghibli",
          score: 40,
          question:
            "What is the name of the moving castle in 'Howl's Moving Castle'?",
          answer: "Howl's Castle",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 14,
          showName: "Studio Ghibli",
          score: 50,
          question: "Who directed most Studio Ghibli films?",
          answer: "Hayao Miyazaki",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
      ],
    },
    {
      name: "Classic Anime",
      imgUrl:
        "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dBsDWUcdfbuZwglgyeeQ9ChRoS4.jpg",
      questions: [
        {
          questionId: 15,
          showName: "Classic Anime",
          score: 10,
          question: "What is the name of the main character in 'Astro Boy'?",
          answer: "Astro",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 16,
          showName: "Classic Anime",
          score: 20,
          question: "What year was the original 'Mobile Suit Gundam' released?",
          answer: "1979",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 17,
          showName: "Classic Anime",
          score: 20,
          question:
            "What is the name of the bounty hunter ship in 'Cowboy Bebop'?",
          answer: "Bebop",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 18,
          showName: "Classic Anime",
          score: 30,
          question: "Who is the main antagonist in 'Akira'?",
          answer: "Tetsuo Shima",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 19,
          showName: "Classic Anime",
          score: 40,
          question:
            "What is the name of the organization in 'Neon Genesis Evangelion'?",
          answer: "NERV",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 20,
          showName: "Classic Anime",
          score: 50,
          question: "What is the name of the mecha in 'Mobile Suit Gundam'?",
          answer: "RX-78-2 Gundam",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
      ],
    },
    {
      name: "Isekai Anime",
      imgUrl:
        "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dBsDWUcdfbuZwglgyeeQ9ChRoS4.jpg",
      questions: [
        {
          questionId: 21,
          showName: "Isekai Anime",
          score: 10,
          question: "What is the name of the protagonist in 'Re:Zero'?",
          answer: "Subaru Natsuki",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 22,
          showName: "Isekai Anime",
          score: 10,
          question: "What is the name of the MMORPG in 'Sword Art Online'?",
          answer: "Sword Art Online",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 23,
          showName: "Isekai Anime",
          score: 20,
          question:
            "What is the name of the slime in 'That Time I Got Reincarnated as a Slime'?",
          answer: "Rimuru Tempest",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 24,
          showName: "Isekai Anime",
          score: 30,
          question: "Who is the main character in 'No Game No Life'?",
          answer: "Sora and Shiro",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 25,
          showName: "Isekai Anime",
          score: 40,
          question:
            "What is the name of the shield hero in 'The Rising of the Shield Hero'?",
          answer: "Naofumi Iwatani",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 26,
          showName: "Isekai Anime",
          score: 50,
          question: "What is the name of the demon lord in 'Overlord'?",
          answer: "Ainz Ooal Gown",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
      ],
    },
    {
      name: "Sports Anime",
      imgUrl:
        "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dBsDWUcdfbuZwglgyeeQ9ChRoS4.jpg",
      questions: [
        {
          questionId: 27,
          showName: "Sports Anime",
          score: 10,
          question: "What sport is featured in 'Haikyuu!!'?",
          answer: "Volleyball",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 28,
          showName: "Sports Anime",
          score: 10,
          question:
            "What is the name of the main character in 'Kuroko no Basket'?",
          answer: "Tetsuya Kuroko",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 29,
          showName: "Sports Anime",
          score: 20,
          question:
            "What is the name of the cycling anime featuring Onoda Sakamichi?",
          answer: "Yowamushi Pedal",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 30,
          showName: "Sports Anime",
          score: 30,
          question:
            "What is the name of the boxing anime featuring Ippo Makunouchi?",
          answer: "Hajime no Ippo",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 31,
          showName: "Sports Anime",
          score: 40,
          question:
            "What is the name of the swimming anime featuring Haruka Nanase?",
          answer: "Free!",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 32,
          showName: "Sports Anime",
          score: 50,
          question:
            "What is the name of the soccer anime featuring Tsubasa Ozora?",
          answer: "Captain Tsubasa",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
      ],
    },
    {
      name: "Mecha Anime",
      imgUrl:
        "https://image.tmdb.org/t/p/w600_and_h900_bestv2/dBsDWUcdfbuZwglgyeeQ9ChRoS4.jpg",
      questions: [
        {
          questionId: 33,
          showName: "Mecha Anime",
          score: 10,
          question: "What is the name of the main mecha in 'Code Geass'?",
          answer: "Lancelot",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 34,
          showName: "Mecha Anime",
          score: 10,
          question: "Who pilots the EVA Unit-01 in 'Neon Genesis Evangelion'?",
          answer: "Shinji Ikari",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 35,
          showName: "Mecha Anime",
          score: 20,
          question: "What is the name of the mecha in 'Gurren Lagann'?",
          answer: "Gurren Lagann",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 36,
          showName: "Mecha Anime",
          score: 30,
          question:
            "What is the name of the main Gundam in 'Mobile Suit Gundam Wing'?",
          answer: "Wing Gundam",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 37,
          showName: "Mecha Anime",
          score: 40,
          question: "Who is the main antagonist in 'Code Geass'?",
          answer: "Charles zi Britannia",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
        {
          questionId: 38,
          showName: "Mecha Anime",
          score: 50,
          question:
            "What is the name of the space colony in 'Mobile Suit Gundam'?",
          answer: "Side 7",
          hints: [],
          shownHints: [],
          awardedPlayerId: -1,
          answerRevealed: false,
          questionShown: false,
        },
      ],
    },
  ];
};
